### ISSUE TITLE
Define the links between different forms for the gameplay.

### ISSUE THREAD

**Issue by ScarlandianProgrammer** [JohnnyBee86/DataDrivenDungeon#2]
- [x] Start up form (Home Screen, New Game, etc...).
- [x] Hub world form (Each shop, the bank and dungeons).
- [x] 1 form for each shop and 1 for the bank (Options to buy, to sell, and to leave [Magic shop has random quantities available] [The armory is progression-based]).
- [x] Dungeon form (Fighting enemies [Pokemon-style fight menu], opens another form telling you whether you won or lost).
