### ISSUE TITLE
Make a database model for item, enemy, and game objects.

### ISSUE THREAD

**Issue by JohnnyBee86** [JohnnyBee86/DataDrivenDungeon#3]
- [x] Plan the database
- [x] Script Model Classes
- [x] Script DbContext
- [x] Create Initial migration
